version: Build No. {build}
configuration: Release
platform: x64
install:
- cd sdk/
- 'echo Downloading ScriptHook [Version: 1.0.350.2b]'
- appveyor DownloadFile http://dl.johnnycrazy.de/scripthook/ScriptHookV_SDK_1.0.350.2b.zip -FileName sdk.zip
- echo Download completed. Extracting...
- 7z x sdk.zip
- echo Extraction complete
- cd ../
build:
  project: ScriptHookVDotNet.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin/Release/
  name: ScriptHookVDotNet
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: ScriptHookVDotNet $(appveyor_repo_tag_name)
  auth_token:
    secure: yXWwz+eBEafzOqCBMb7z/gvhR9eZ5YZuCgwtvZ6UiCyA8tWabAEjQadromc7f7vM
  artifact: ScriptHookVDotNet
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
