contact_links:
  - name:  Script Hook V Issue for New Game Version
    url: http://www.dev-c.com/gtav/scripthookv/
    about: |
      This issue tracker is not for the Script Hook V issue where "FATAL: Unknown game version" appears,  Please be patient until a new ScriptHookV update is released.
  - name: 🤔 Questions and Help
    url: https://discord.gg/2PR7aMzD4U
    about: This issue tracker is not for support questions. Please seek your support help in other communities, such as 5Mods Discord server or its forum. The link will invite you to 5Mods Discord server for the time being.