name: Build

on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
        vs-version: 16.1.6
    - name: Install ScriptHookV SDK
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: ./tools/install_sdk.ps1
    - name: Define SHVDN version
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git fetch --unshallow
        echo "SHVDN_VERSION=$(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" refs/tags |% { $_.Substring(1) })" >> $Env:GITHUB_ENV
        echo "Version: ${{env.SHVDN_VERSION}}"
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    - name: Build solution and put misc files for packing
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:configuration=Release /p:platform=x64 ScriptHookVDotNet.sln `
        && del bin\Release\ScriptHookVDotNet*.metagen `
        && type README.md | more /P > bin\Release\README.txt `
        && type LICENSE.txt | more /P > bin\Release\LICENSE.txt `
        && echo ReloadKey=None > bin\Release\ScriptHookVDotNet.ini `
        && echo ConsoleKey=F4 >> bin\Release\ScriptHookVDotNet.ini `
        && echo ScriptTimeoutThreshold=5000 >> bin\Release\ScriptHookVDotNet.ini `
        && echo WarnOfDeprecatedScriptsWithTicker=true >> bin\Release\ScriptHookVDotNet.ini
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: bin/Release/*
  create-release-draft:
    runs-on: windows-latest
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    permissions:
      contents: write
    steps:
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: 7z a ${{ github.event.repository.name }}-${{ github.event.ref }}.zip ${{ github.workspace }}/bin/Release/*
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ScriptHookVDotNet ${{ github.event.ref }}
          files: ${{ github.event.repository.name }}-${{ github.event.ref }}.zip
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN_GITHUB }}