name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64
        vs-version: 16.1.6
    - name: Install ScriptHookV SDK
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: ./tools/install_sdk.ps1
    - name: Define SHVDN version
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git fetch --unshallow
        echo "SHVDN_VERSION=$(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" refs/tags |% { $_.Substring(1) })" >> $env:GITHUB_ENV
        echo "Version: ${{env.SHVDN_VERSION}}"
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    - name: Build solution and put misc files for packing
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:configuration=Release /p:platform=x64 ScriptHookVDotNet.sln `
        && del bin\Release\ScriptHookVDotNet*.metagen `
        && type README.md | more /P > bin\Release\README.txt `
        && type LICENSE.txt | more /P > bin\Release\LICENSE.txt `
        && echo ReloadKey=None > bin\Release\ScriptHookVDotNet.ini `
        && echo ConsoleKey=F4 >> bin\Release\ScriptHookVDotNet.ini `
        && echo ScriptTimeoutThreshold=5000 >> bin\Release\ScriptHookVDotNet.ini `
        && echo WarnOfDeprecatedScriptsWithTicker=true >> bin\Release\ScriptHookVDotNet.ini
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ScriptHookVDotNet
        path: bin/Release/*
  create-release-draft:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ScriptHookVDotNet
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: |
          echo "TAG_VERSION_NAME=$($env:GITHUB_REF.Substring(10))" >> $env:GITHUB_ENV
      - run: 7z a ScriptHookVDotNet-${{ env.TAG_VERSION_NAME }}.zip ${{ github.workspace }}/bin/Release/*
      - uses: ncipollo/release-action@v1.12.0
        with:
          name: ScriptHookVDotNet ${{ env.TAG_VERSION_NAME }}
          artifacts: |
            ScriptHookVDotNet-${{ env.TAG_VERSION_NAME }}.zip
          draft: true
          artifactErrorsFailBuild: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          token: ${{ secrets.RELEASE_TOKEN_GITHUB }}
