name: 🌕🏭 Create Nightly Release

on:
  push:
    branches:
      - 'main'
    tags:
      # create nightly releases for
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      semver_name:
        description: 'Custom version tag name without v prefix'
        required: false
        type: string

permissions:
  contents: read

jobs:
  calc-next-tag-name:
    name: Calculate New Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ format('{0}/scripthookvdotnet-nightly', github.repository_owner) }}
          path: nightly-repo
          fetch-depth: 0
        env:
          CUSTOM_TAG_NAME: ${{ github.event_name != workflow_dispatch && github.event.inputs.tag_name || '' }}
        run: |
          if [ "$CUSTOM_VERSION_NAME" != "" ]; then
            echo "next_version_name=$CUSTOM_VERSION_NAME" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          if [[ "$GITHUB_REF" = refs/tags/* ]]; then
            # we've already checked that the ref is a tag with the v prefix
            next_version_name=$(echo "$GITHUB_REF_NAME" | cut -c2-)
            echo "next_version_name=$next_version_name" >> "$GITHUB_OUTPUT"
           exit 0
          fi

          if latest_tag_name=$(git describe --tags `git rev-list --tags --max-count=1`); then
            next_version_name=$(npx semver "$latest_tag_name" -i prerelease)
            echo "next_version_name=$next_version_name" >> "$GITHUB_OUTPUT"
          else
            echo "There's no tags on the nightly repo. Please specify a custom version tag."
            exit 1
          fi

  create-new-tag:
    needs: calc-next-tag-name
    name: Push New Version Tag
    runs-on: ubuntu-latest
    uses: mathieudutour/github-tag-action@v6.1
    with:
      github_token: ${{ secrets.RELEASE_TOKEN_NIGHTLY }}
      # needs to allow any refs so the action won't skip creating a tag when a tag ref is pushed
      release_branches: ".*"
      create_annotated_tag: true
      custom_tag: ${{ jobs.calc-next-tag-name.outputs.next_version_name }}

  create-release-note-body-text:
    name: Create Body Text for Release
    runs-on: ubuntu-latest
    uses: actions/github-script@v7
    with:
      script: |
        const commitSha = ${{ github.sha }};

        console.log(`Searching for Commit - ${commitSha}`);

        const { data: commit } = github.rest.repos.getCommit({
          owner: context.repo.owner,
          repo: context.repo.repo,
          ref: commitSha,
        });

        return `- [${commit.commit.message}](${commit.html_url})\n`;
      result-encoding: string

  build:
    name: Build Solution
    uses: ./.github/workflows/build.yml
    # can't (directly) pass property values of the env var for reusable workflows, so build workflow takes care

  create-release:
    name: Publish Release
    needs: [create-new-tag, create-release-note-body-text, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from build Workflow
        uses: actions/download-artifact@v3
        with:
          name: ScriptHookVDotNet
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - name: Pack build
        run: |
          $artifact_name = "ScriptHookVDotNet-${GITHUB_REF_NAME}"
          $artifact_file_name = "${artifact_name}.zip"
          "artifact_name=${artifact_name}" >> $GITHUB_ENV
          "artifact_filename=${artifact_file_name}" >> $GITHUB_ENV
          7z a "$artifact_file_name" ${{ github.workspace }}/bin/Release/*
      - name: Push new release
        uses: ncipollo/release-action@v1.13.0
        with:
          repo: scripthookvdotnet-nightly
          name: ${{ env.artifact_name }}
          token: ${{ secrets.RELEASE_TOKEN_NIGHTLY }}
          body: ${{ jobs.create-release-note-body-text.outputs.result }}
          artifacts: |
            ${{ env.artifact_filename }}
          artifactErrorsFailBuild: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
